# Generated by Django 4.2.6 on 2023-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day',
            field=models.DateField(),
        ),
    ]
